diary/urls.py
from django.urls import path

from . import views


app_name = 'diary'
urlpatterns = [
    path('',views.IndexView.as_view(),name="index"),
    path('inquiry/',views.InquiryView.as_view(),name="inquiry"),
    path('diary-list/',views.DiaryListView.as_view(),name="diary_list"),
    path('diary-detail/<int:pk>/',views.DiaryDetailView.as_view(),name="diary_detail"),
    path('diary-create/',views.DiaryCreateView.as_view(),name="diary_create"),
    path('diary_update/<int:pk>/',views.DiaryUpdateView.as_view(),name='diary_update'),
    path('diary-delete/<int:pk>/',views.DiaryDeleteView.as_view(),name="diary_delete"),
]

private_diary/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include

from . import settings_common, settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('diary.urls')),
    path('accounts/',include('allauth.urls')),
]
#開発サーバでメディアを配信できるようにする設定
urlpatterns += static(settings_common.MEDIA_URL,document_root = settings_dev.MEDIA_ROOT)

accounts/models.py
from django.db import models

from django.contrib.auth.models import  AbstractUser

# Create your models here.

class CustomUser(AbstractUser):
    """拡張ユーザーモデル"""

    class Meta:
        verbose_name_plural = 'CustomUser'

diary/models.py
from accounts.models import CustomUser
from django.db import models
# Create your models here.

class Diary(models.Model):

    user = models.ForeignKey(CustomUser, verbose_name='ユーザー',on_delete=models.PROTECT)
    title = models.CharField(verbose_name='title',max_length=40)
    content = models.TextField(verbose_name='本文',blank=True,null=True)
    photo1 = models.ImageField(verbose_name='写真1',blank=True,null=True)
    photo2 = models.ImageField(verbose_name='写真2', blank=True, null=True)
    photo3 = models.ImageField(verbose_name='写真3', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時',auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時',auto_now=True)

    class Meta:
        verbose_name_plural = 'Diary'

    def __str__(self):
        return self.title

diary/forms.py
from django import forms
from .models import Diary
from django.core.mail import EmailMessage

class InquiryForm(forms.Form):
    name = forms.CharField(label='お名前',max_length=30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル',max_length=30)
    message = forms.CharField(label='メッセージ',widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control col-9'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前をここに入力してください。'

        self.fields['email'].widget.attrs['class'] = 'form-control col-11'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください。'

        self.fields['title'].widget.attrs['class'] = 'form-control col-11'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください。'

        self.fields['message'].widget.attrs['class'] = 'form-control col-12'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください。'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ {}'.format(title)
        message = '送信者名: {0}\nメールアドレス: {1}\nメッセージ:\n{2}'.format(name,email,message)
        from_email = 'admin@example.com'
        to_list = [
            'test@example.com'
        ]
        cc_list = [
            email
        ]

        message = EmailMessage(subject=subject, body=message, from_email=from_email,to=to_list,cc=cc_list)
        message.send()

class DiaryCreateForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = ('title','content','photo1','photo2','photo3')

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in self.fields.values():
                field.widget.attrs['class'] = 'form-control'

accounts/views.py
from django.shortcuts import render

# Create your views here.

diary/views.py
import logging

from .forms import  DiaryCreateForm

from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib import messages

from django.urls import reverse_lazy

from django.views import generic

from .forms import InquiryForm

from .models import Diary

logger = logging.getLogger(__name__)

# Create your views here.

class IndexView(generic.TemplateView):
    template_name = "index.html"

class InquiryView(generic.FormView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy('diary:inquiry')

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request,'メッセージを送信しました。')
        logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))
        return super().form_valid(form)

class DiaryListView(LoginRequiredMixin,generic.ListView):
    model = Diary
    template_name = 'diary_list.html'
    paginate_by = 2

    def get_query(self):
        diaries = Diary.objects.filter(user=self.request.user).order_by('-created_at')
        return diaries

class DiaryDetailView(LoginRequiredMixin, generic.DetailView):
    model = Diary
    template_name = 'diary_detail.html'

class DiaryUpdateView(LoginRequiredMixin,generic.UpdateView):
    model = Diary
    template_name = 'diary_update.html'
    form_class = DiaryCreateForm

    def get_success_url(self):
        return reverse_lazy('diary:diary_detail',kwargs={'pk' : self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request,'日記を更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request,"日記の更新に失敗しました。")
        return super().form_valid(form)


class DiaryCreateView(LoginRequiredMixin, generic.CreateView):
    model = Diary
    template_name = 'diary_create.html'
    form_class = DiaryCreateForm
    success_url = reverse_lazy('diary:diary_list')

    def form_valid(self, form):
        diary = form.save(commit=False)
        diary.user = self.request.user
        diary.save()
        messages.success(self.request,'日記を作成しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request,"日記の作成に失敗しました。")
        return super().form_invalid(form)

class DiaryDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Diary
    template_name = 'diary_delete.html'
    success_url = reverse_lazy('diary:diary_list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request,"日記を削除しました。")
        return super().delete(request, *args, **kwargs)

diary/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title%}{% endblock %}</title>

    <!--Bootstrap core CSS-->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!--Custom fonts for this template-->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

    <!--Custom styles for this template-->
    <link href="{% static 'css/one-page-wonder.min.css' %}" rel="stylesheet">

    <!--My style-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
    <div id="wrapper">
        <!--Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'diary:index' %}">PRIVATE DIARY</a>
                <button class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navbarResponsive"
                        aria-controls="navbarResponsive"
                        aria-expanded="false"
                        aria-label="Toggle navigation">

                    <span class="navbar-toggler-icon"></span>

                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item {% block active_inquiry %}{% endblock %}">
                            <a class="nav-link" href="{% url 'diary:inquiry' %}">INQUIRY</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item {% block active_diary_list %}{% endblock %}">
                            <a class="nav-link" href="{% url 'diary:diary_list' %}">DIARY LIST</a>
                        </li>
                        {% endif %}
                    </ul>


                    <ul class="navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
                        </li>
                        {% else %}
                        <li class="nav-item {% block active_signup %}{% endblock %}">
                            <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                        </li>
                        <li class="nav-item {% block active_login %}{% endblock %}">
                            <a class="nav-link" href="{% url 'account_login' %}">Log In</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        {% block header%}{% endblock %}

        {% if messages %}
        <div class="container">
            <div class="row">
                <div class="my-div-style w-100">
                    <ul class="messages" style="list-style: none;">
                        {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                            {{ message }}
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        {% endif %}

        {% block contents%}{% endblock %}

        <!--Footer-->
        <footer class="py-5 bg-black">
            <div class="container">
                <p class="m-0 text-center  text-white small">Copyright &copy; Private Diary 2020</p>
            </div>
            <!--/.container-->
        </footer>

        <!--Bootstrap core JavaScript-->
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    </div>
</body>

</html>

diary/templates/diary_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}日記作成|Private Diary{% endblock %}
{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST"  enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">作成</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

diary/templates/diary_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}日記削除|Private Diary{% endblock %}
{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST">
                {% csrf_token %}
                <p>本当に削除しますか</p>
                <button class="btn btn-primary mt-5" type="submit">削除</button>
                <a class="btn btn-secondary mt-5 ml-2" href="{% url 'diary:diary_detail' object.pk %}">キャンセル</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

diary/templates/diary_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}日記詳細|Private Diary{% endblock %}
{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="my-div-style w-100">
        <div class="row">
            <div class="col-3">
                <strong>タイトル</strong>
            </div>

            <div class="col-9">
                {{ object.title }}
            </div>
        </div>
        <hr>

        <div class="row">
            <div class="col-3">
                <strong>本文</strong>
            </div>

            <div class="col-9">
                {{ object.content|linebreaksbr }}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>写真</strong>
            </div>
            <div class="col-3">
                {% if object.photo1 %}
                <img src="{{ object.photo1.url }}" width="200" height="200" />
                {% endif %}
            </div>
            <div class="col-3">
                {% if object.photo2 %}
                <img src="{{ object.photo2.url }}" width="200" height="200" />
                {% endif %}
            </div>
            <div class="col-3">
                {% if object.photo3 %}
                <img src="{{ object.photo3.url }}" width="200" height="200" />
                {% endif %}
            </div>

        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>作成日時</strong>
            </div>
            <div class="col-9">
                {{ object.created_at }}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>更新日時</strong>
            </div>
            <div class="col-9">
                {{ object.updated_at }}
            </div>
        </div>
        <a class="btn btn-success mt-5 mb-3" href="{% url 'diary:diary_update' object.pk %}">編集</a>
        <a class="btn btn-danger mt-5 ml-2 mb-3" href="{% url 'diary:diary_delete' object.pk %}">削除</a>
    </div>
</div>
{% endblock %}

diary/templates/diary_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}日記一覧|Private Diary{% endblock %}
{% block active_diary_list %}active{% endblock %}
{% block head %}
<link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="clearfix">
                    <a class="btn btn-primary float-right" href="{% url 'diary:diary_create' %}">新規作成</a>
                </div>
                {% for diary in diary_list %}
                <div class="post-preview">
                    <a href="{% url 'diary:diary_detail' diary.pk %}">
                        <h2 class="post-title">
                            {{ diary.title }}
                        </h2>
                        <h3 class="post-subtitle">
                            {{ diary.content|truncatechars:20 }}
                        </h3>
                    </a>
                    <p class="post-meta">{{ diary.created_at }}</p>
                </div>
                <hr>
                {% empty %}
                <p>日記がありません。</p>
                {% endfor %}

                <!--ページネーション処理-->
                {% if is_paginated %}
                <ul class="pagination">
                    <!--前ページへのリンク-->
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% endif %}


                <!--ページ数表示-->
                {% for page_num in page_obj.paginator.page_range %}
                {% if page_obj.number == page_num %}
                <li class="page-item active">
                    <a class="page-link" href="#">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                </li>
                {% endif %}
                {% endfor %}

                <!--次ページへのリンク-->
                {% if page_obj.has_next %}
                <li class="page_item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
                </ul>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

diary/templates/diary_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}日記編集|Private Diary{% endblock %}
{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST"  enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">更新</button>
                <a class="btn btn-secondary ml-2" href="{% url  'diary:diary_detail' object.pk %}">キャンセル</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

diary/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Web上にあなた専用の日記ページを保存できるサービス | Private Diary{% endblock %}

{% block header %}

<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="conatiner">
            <h1 class="masthead-heading mb-0">Private Diary</h1>
            <h2 class="masthead-subheading mb-0">you専用の日記保存サービス</h2>
            <a href="{% url 'account_login' %}" class="btn btn-primary btn-xl rounded-pill mt-5">LOG IN</a>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}
{% block contents %}
<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'img/01.jpg' %}" alt="">
                </div>
            </div>

            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">Web Diary</h2>
                    <p>ウェブ上で作成/編集/削除ができる日記</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'img/02.jpg' %}" alt="">
                </div>
            </div>

            <div class="col-lg-6">
                <div class="p-5">
                    <h2 class="display-4">Ssave Your Diary</h2>
                    <p>あなたの日記をウェブに保存</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'img/03.jpg' %}" alt="">
                </div>
            </div>

            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">Membership System</h2>
                    <p>会員制のWeb日記サービス</p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

diary/templates/inquiry.html
{% extends 'base.html' %}

{% block title %}お問い合わせ｜Private Diary{% endblock %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}

<div class="container">
    <div class="row">
        <div class="my-div-style" >
            <!--style="margin-top:6rem;"-->
            <form method="post">
                {% csrf_token %}

                {{ form.non_field_errors }}

                {% for field in form %}
                    <div class="from-group row">
                        <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">
                            <strong>{{ field.label_tag }}</strong>
                        </label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}

                <div class="offset-sm-4 col-sm-8">
                    <button class="btn btn-primary" type="submit">送信</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}